### PR TITLE
A addition code_to_session function.

### PR DESCRIPTION
**Pull request by SeverusWell**
> code_to_session( js_code)

  登录凭证校验。通过 wx.login() 接口获得临时登录凭证 code 后传到开发者服务器调用此接口完成登录流程。更多使用方法详见 小程序登录,详情请参考https://developers.weixin.qq.com/miniprogram/dev/api/code2Session.html

参数

- js_code **( str)** – js_code 为 登录时获取的 code。

| 属性    | 类型   | 说明              |
| ------- | ------ | ----------------- |
| js_code | string | 登录时获取的 code |

返回:

| 属性        | 类型   | 说明                                                         |
| ----------- | ------ | ------------------------------------------------------------ |
| openid      | string | 用户唯一标识                                                 |
| session_key | string | 会话密钥                                                     |
| unionid     | string | 用户在开放平台的唯一标识符，在满足 UnionID 下发条件的情况下会返回，详见 [UnionID 机制说明](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/union-id.html)。 |
| errcode     | number | 错误码                                                       |
| errmsg      | string | 错误信息                                                     |

示例

```
from wechatpy import WeChatClient
client = WeChatClient('appid', 'secret')
js_code = ''
client.wxa.code_to_session(js_code)
```

### CODE REVIEW

**Comment by messense** [comment]
Mostly LGTM, can you add a test case?

**Comment by SeverusWell** [comment]
Of course, I'll try it later. This is my first time writing a python test case😆

**Comment by messense** [comment]
Steps:

1. Add the test case in file https://github.com/jxtech/wechatpy/blob/master/tests/test_client.py
2. The outgoing request should be mocked, put the json file in https://github.com/jxtech/wechatpy/tree/master/tests/fixtures (mock is done by https://github.com/jxtech/wechatpy/blob/master/tests/test_client.py#L20)

**Comment by SeverusWell** [comment]
Thank you for your help,I added this test case in file `test_client.py`,Everything seems fine.

**Review by messense — APPROVED** [review]
LGTM

**Comment by messense** [comment]
Thanks!

**Comment by SeverusWell** [comment]
Thank you for your help, I am very helpful to help more people.

**Comment by cougarwww** [comment]
这个接口实际是用不到access_token，这么写后会去取access_token

**Comment by SeverusWell** [comment]
> 这个接口实际是用不到access_token，这么写后会去取access_token

写这个方法主要是想拿到unionID,顺便也换回了access_token.如果能够只换到unionID就完美了

**Comment by cougarwww** [comment]
刚才仔细看了下 get 的 params参数里加个 'access_token':"", 就不会去主动取access_token了

**Pull request merged**
