### PR TITLE
bugfix #99

### PR DESCRIPTION
**Pull request by hunter007**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: b27626b1fa1d70c2da9cbbd15b743eea12edf4c9
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**
  - Your subject line is longer than 72 characters
- Commit: fa0d855f883f1ad6b4b3c5a5a14ebffb6bb2e19a
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**
  - Your subject line is longer than 72 characters

Guidelines are available at https://github.com/jxtech/wechatpy/blob/master/CONTRIBUTING.md

---

This message was auto-generated by https://gitcop.com

**Comment by messense** [comment]
Thanks!

**Comment by hunter007** [comment]
BaseWeChatComponent增加了token 和encoding_aes_key，造成不能和之前版本的BaseWeChatComponent兼容，请发布新版本。

**Comment by messense** [comment]
嗯，还有需要更新下测试用例~

**Comment by messense** [comment]
所有的 builds 都 failed 了

**Pull request merged**
