### PR TITLE
Add new customer service message type `miniprogrampage`

### PR DESCRIPTION
**Pull request by tssujt**

### CODE REVIEW

**Comment by liriansu-opus** [comment]
please fix ci

**Comment by messense** [comment]
> please fix ci

You can fix CI by rebase onto v1.

**Comment by tssujt** [comment]
@LKI @messense What about DeepSource Error? I have no idea about how to fix that.

**Comment by messense** [comment]
> @LKI @messense What about DeepSource Error? I have no idea about how to fix that.

You can ignore that.

**Review by messense — APPROVED** [review]
Thanks!

**Comment by tssujt** [comment]
@messense IMHO, you could cherry-pick this commit to master.

**Comment by messense** [comment]
> @messense IMHO, you could cherry-pick this commit to master.

Just did that.

**Pull request merged**
