### PR TITLE
component 文档更新

### PR DESCRIPTION
**Pull request by hunter007**
component 文档更新  [ci skip]

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 8e0defc046d80a60cdcdaf3a14f5d22ec505b8d7
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/jxtech/wechatpy/blob/master/CONTRIBUTING.md

---

This message was auto-generated by https://gitcop.com

**Comment by messense** [comment]
顺便更新下 test cases 吧

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 8e0defc046d80a60cdcdaf3a14f5d22ec505b8d7
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**
- Commit: 35885791206ffea3161a07a00a7ef78decf01231
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/jxtech/wechatpy/blob/master/CONTRIBUTING.md

---

This message was auto-generated by https://gitcop.com

**Comment by messense** [comment]
有一些测试没修复

**Pull request merged**
