### PR TITLE
企业号摇一摇 API

### PR DESCRIPTION
**Pull request by cloverstd**
http://qydev.weixin.qq.com/wiki/index.php?title=获取设备及用户信息

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 197d834b6d35b2264e15a2cf414719a2e851c05a
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/jxtech/wechatpy/blob/master/CONTRIBUTING.md

---

This message was auto-generated by https://gitcop.com

**Comment by messense** [comment]
Thanks.

**Comment by cloverstd** [comment]
@messense 

`%{type}(%{scope}): %{description}` 其中的 type 和 scope 分别指什么？

**Comment by messense** [comment]
@cloverstd https://gitcop.com/

**Comment by messense** [comment]
the variables %{type}, %{scope} and %{description} can be used 
any other characters will be interpreted literally. The subject 
fix(user): ensure email is required 
%{type}(%{scope}): %{description} 
would match type: fix, scope: user, description: ensure email is required

**Comment by messense** [comment]
image

**Comment by cloverstd** [comment]
@messense 👌，Thanks

**Pull request merged**
